services:
  movie-app:
    build: .
    ports:
      - "3001:3001"
    environment:
      HOST: mysql_db
      databasename: user
      PASSWORD: password
      DATABASE: mydatabase                         
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
